### ISSUE TITLE
i am big investor.

### ISSUE THREAD

**Issue by kero3009destiny** [Onani-Dev/Onani#47]
hello i am famous investor gary vee, you need to make site compatible with the famous operating system Windows NT so famous developers like dirt 1009 and matlur0004 can work on this project.

**Comment by ghost** [comment]
very true i am the collaborator of this epic man and very needing the windows support !!

**Comment by kero3009destiny** [comment]
I can use docker on my laptop.

**Comment by kapsikkum** [comment]
:)
