### ISSUE TITLE
(BAN-B104) Binding to all interfaces detected with hardcoded values

### ISSUE THREAD

**Issue by kero3009destiny** [Onani-Dev/Onani#53]
I think Dockers blocks outside access to direct Flask, even then we will have Cloudflare bla bla bla. Close issue if it is how it is @kapsikkum 

## Description
Binding to all network interfaces can potentially open up a service to traffic on unintended interfaces, that may not be properly documented or secured. This can be prevented by changing the code so it explicitly only allows access from localhost. Correct code:

## Occurrences
There is 1 occurrence of this issue in the repository. 

fuck you,, it is at run.py ofc. See all occurrences on DeepSource &rarr; [deepsource.io/gh/Onani-Dev/Onani/issue/BAN-B104/occurrences/](https://deepsource.io/gh/Onani-Dev/Onani/issue/BAN-B104/occurrences/)

**Comment by kapsikkum** [comment]
What
