### ISSUE TITLE
ONANI REQUIRED FEATURES

### ISSUE THREAD

**Issue by kapsikkum** [Onani-Dev/Onani#70]
# Logic
- [x] #83
- [x] #73
- [x] #81
- [x] #82
- [x] #84
- [x] #85
- [x] #87
- [ ] #89
- [ ] #90
- [x] #93
- [x] #95
- [ ] #74

# Pages
- [x] #102
- [x] #99
- [x] #100
- [x] #97
- [ ] #96
- [x] #105
- [x] #92
- [x] #91

# Other
- [ ] #86
- [x] #88

# Heavylifting
- [ ] #101
- [x] #103
- [x] #104

**Comment by kapsikkum** [comment]
https://www.section.io/engineering-education/implementing-totp-2fa-using-flask/

**Comment by kapsikkum** [comment]
https://pypi.org/project/flask-crontab/

**Comment by ghost** [comment]
Closing since i moved everything to kanban
